### ISSUE TITLE
How to change file or folder color if I type "cd"?

### ISSUE THREAD

**Issue by dongxi8** [ohmybash/oh-my-bash#360] opened 2022-09-24 03:09 UTC
Now the color is dark blue, and I can not see it clearly cause of the color.

How to change this color?

![image](https://user-images.githubusercontent.com/1157840/192077489-56b4199b-ba09-45c9-b3a3-67279604dae5.png)

**Comment by akinomyoga** [comment] 2022-09-24 04:11
I assume you are using `ble.sh`. You can configure it in `~/.blerc` using `ble-face`. For example,

```bash
# blerc

ble-face command_directory='fg=33,underline'
ble-face filename_directory='fg=33,underline'
```

The color index (such as 33 in the above example) can be listed by the following command:

```bash
$ ble palette
```

**Comment by dongxi8** [comment] 2022-09-24 07:14
> I assume you are using `ble.sh`. You can configure it in `~/.blerc` using `ble-face`. For example,
> 
> ```shell
> # blerc
> 
> ble-face command_directory='fg=33,underline'
> ble-face filename_directory='fg=33,underline'
> ```
> 
> The color index (such as 33 in the above example) can be listed by the following command:
> 
> ```shell
> $ ble palette
> ```

tks very much

it works

**Comment by dongxi8** [comment] 2022-09-24 07:15
after I update the ble to the latest version, some issue appears, like this:

![image](https://user-images.githubusercontent.com/1157840/192085348-5c4b34a5-425f-45c7-bbc1-c4007dda4b7d.png)

**Comment by akinomyoga** [comment] 2022-09-24 08:49
Which terminal do you use? Could you paste the result of pressing <kbd>C-x C-v</kbd> (i.e., press Ctrl+X and then Ctrl+V)?

**Comment by dongxi8** [comment] 2022-09-24 09:52
> Which terminal (and version) do you use? Could you paste the result of pressing C-x C-v (i.e., press Ctrl+X and then Ctrl+V)?


GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu) [Ubuntu 16.04.7 LTS]
ble.sh, version 0.4.0-devel3+49e55f4 (noarch)
oh-my-bash (powerline), version 1.0.0+f52647d6 (noarch), aliases(general), completions(git composer ssh), plugins(git bashmarks)
locale: LANG=en_US.UTF-8 LC_ADDRESS=zh_CN.UTF-8 LC_CTYPE=en_US.UTF-8 LC_IDENTIFICATION=zh_CN.UTF-8 LC_MEASUREMENT=zh_CN.UTF-8 LC_MONETARY=zh_CN.UTF-8 LC_NAME=zh_CN.UTF-8 LC_NUMERIC=zh_CN.UTF-8 LC_PAPER=zh_CN.UTF-8 LC_TELEPHONE=zh_CN.UTF-8 LC_TIME=zh_CN.UTF-8
terminal: TERM=xterm-256color wcwidth=8.0-west/15.0-2+ri, vte:4205 (1;4205;0)

**Comment by akinomyoga** [comment] 2022-09-30 01:59
Sorry for the delay. I have identified the cause and fixed it locally but haven't yet tested enough with actual different terminals. I don't have enough time to test it now. I'll try to find time today. Thank you for your patience.

**Comment by akinomyoga** [comment] 2022-10-01 23:30
@dongxi8 Sorry for the delay. I have pushed a fix https://github.com/akinomyoga/ble.sh/commit/149eee9237814ac0b2c53af8439164da0211e07f. Could you update ble.sh by `ble-update` and check the fix?

**Comment by dongxi8** [comment] 2022-10-08 03:41
> @dongxi8 Sorry for the delay. I have pushed a fix [akinomyoga/ble.sh@149eee9](https://github.com/akinomyoga/ble.sh/commit/149eee9237814ac0b2c53af8439164da0211e07f). Could you update ble.sh by `ble-update` and check the fix?

it works. THKS

**Comment by akinomyoga** [comment] 2022-10-08 05:17
Thanks!

**Closed by akinomyoga** 2022-10-08 05:17 UTC
