### ISSUE TITLE
sh in "$OSH/custom" run twice

### ISSUE THREAD

**Issue by shaynez** [ohmybash/oh-my-bash#409] opened 2023-02-27 16:37 UTC
Put a sh script in $OSH/custom, first login, the sh will run twice;  if source ~/.bashrc, the sh run once.
I think this should be a bug, right?

**Comment by akinomyoga** [comment] 2023-02-27 22:52
Thank you for the report, but I cannot reproduce the problem. What is shown on the startup when you put the following code in `$OSH/custom` (e.g. `$OSH/custom/test.sh`)?

```bash
echo "(${BASH_SOURCE[*]})" >&2
```

**Comment by shaynez** [comment] 2023-02-28 01:54
> Thank you for the report, but I cannot reproduce the problem. What is shown on the startup when you put the following code in `$OSH/custom` (e.g. `$OSH/custom/test.sh`)?
> 
> ```shell
> echo "(${BASH_SOURCE[*]})" >&2
> ```

![image](https://user-images.githubusercontent.com/8834246/221732115-ea80816b-405e-4432-b025-17ee9daccd75.png)
hi, thanks for your reply, please find the output you want in screenshot, btw, git rev is: a35e10c49845539d4b77d0c4cf3897ed17ca1b6a

**Comment by akinomyoga** [comment] 2023-02-28 22:01
Thank you for the information. This means that both `.profile` and `.bash_profile` sources `.bashrc`, and `.bash_profile` also sources `.profile`. Because of this, running `.bash_profile` ended up with sourcing `.bashrc` twice, and thus `oh-my-bash.sh` twice and custom configurations twice.

Can you remove the following part of your `.bash_profile`?

https://github.com/ohmybash/oh-my-bash/blob/1d4ada3d5c38dc57dbc51292aa9bfc2d8e713421/templates/bash_profile.osh-template#L3-L6

**Comment by shaynez** [comment] 2023-03-01 01:16
> Thank you for the information. This means that both `.profile` and `.bash_profile` sources `.bashrc`, and `.bash_profile` also sources `.profile`. Because of this, running `.bash_profile` ended up with sourcing `.bashrc` twice, and thus `oh-my-bash.sh` twice and custom configurations twice.
> 
> Can you remove the following part of your `.bash_profile`?
> 
> https://github.com/ohmybash/oh-my-bash/blob/1d4ada3d5c38dc57dbc51292aa9bfc2d8e713421/templates/bash_profile.osh-template#L3-L6

Yes, you're right, it's ok now. I'm not sure it's Ubuntu(20.04) 's  default setting or Bash's, but it happened, anyway, it's works now, thanks a lot :-）

**Comment by akinomyoga** [comment] 2023-03-01 01:30
> I'm not sure it's Ubuntu(20.04) 's default setting or Bash's,

No, it's actually caused by the `bash_profile` template provided by Oh My Bash. The template is added for macOS (which doesn't provide any bash configurations including `bash_profile` anymore) after the request https://github.com/ohmybash/oh-my-bash/issues/302#issuecomment-1416796333.

I need to think about a way to detect duplicate loading by both `.bash_profile` and `.profile`.

**Comment by shaynez** [comment] 2023-03-02 15:07
> > I'm not sure it's Ubuntu(20.04) 's default setting or Bash's,
> 
> No, it's actually caused by the `bash_profile` template provided by Oh My Bash. The template is added for macOS (which doesn't provide any bash configurations including `bash_profile` anymore) after the request [#302 (comment)](https://github.com/ohmybash/oh-my-bash/issues/302#issuecomment-1416796333).
> 
> I need to think about a way to detect duplicate loading by both `.bash_profile` and `.profile`.

This problem just in Ubuntu for me, my centos8 works fine.

**Comment by akinomyoga** [comment] 2023-03-03 00:58
That is because Ubuntu and CentOS have different default configurations. The problem was that OMB introduced a new configuration that is conflicting with the existing configuration of Ubuntu. This is actually OMB's fault.

I have pushed a fix to avoid adding a conflicting configuration (commit c91a85d), though this doesn't solve the existing installations. Thank you for your report.

**Closed** 2023-04-09 21:44 UTC
