### ISSUE TITLE
Newline and Lesspipe error when terminal opens

### ISSUE THREAD

**Issue by bernie350** [ohmybash/oh-my-bash#296] opened 2022-01-16 12:17 UTC
bash: eval: ligne 6: erreur de syntaxe près du symbole inattendu « newline »
bash: eval: ligne 6: `Usage: lesspipe <file>'

Installed on Gentoo.
![oh-my-bash-error](https://user-images.githubusercontent.com/92715832/149659529-dabfd02f-a5bb-49f4-afd2-26ed1440a735.png)

**Comment by akinomyoga** [comment] 2022-01-16 12:27
This is a duplicate of #46 and #69. #74 is a broken fix. #288 is currently in progress. I believe we can soon merge #288.

**Closed** 2022-01-18 05:15 UTC
Labels: duplicate
