### ISSUE TITLE
Command `which' deprecated

### ISSUE THREAD

**Issue by FajarKim** [ohmybash/oh-my-bash#291] opened 2022-01-10 09:39 UTC
Command 'which'  is deprecated in my terminal. Use command 'command -v' instead of command 'which'.
![Screenshot_2022_0110_163800](https://user-images.githubusercontent.com/86386385/148744788-e11be3c4-4de3-4d44-ad50-6bf3dfc05a06.png)

**Comment by akinomyoga** [comment] 2022-01-10 10:26
Thank you for the report. This is a duplicate of #239, which is currently in progress.

**Closed by akinomyoga** 2022-01-10 10:26 UTC
Labels: duplicate
