### ISSUE TITLE
Some autocompletion features not working in omb

### ISSUE THREAD

**Issue by fangnan99** [ohmybash/oh-my-bash#462] opened 2023-07-31 13:04 UTC
Normally in bash, I was able to get directory autocompletion in python arguments, e.g.
`python some_script.py -p <here normal bash could autocomplete directories>`

With OMB, I don't get this kind of completions anymore

**Comment by akinomyoga** [comment] 2023-07-31 13:55
It's not OMB. As far as I know, OMB doesn't provide completions for `python`, but OMB automatically loads an external library [`bash-completion`](https://github.com/scop/bash-completion) when OMB detects it in the system. The behavior that arguments to a python script do not complete is caused by `bash-completion`.

**Comment by akinomyoga** [comment] 2023-08-07 04:11
The problem was fixed in the upstream bash-completion.

**Closed by akinomyoga** 2023-08-07 04:11 UTC
