### ISSUE TITLE
alias 'd' conflict

### ISSUE THREAD

**Issue by liuhuiping2013** [ohmybash/oh-my-bash#333] opened 2022-06-07 08:26 UTC
in lib/directories.sh
`alias d='dirs -v | head -10'`

in plugins/bashmarks/bashmarks.plugin.sh
`alias d='bm -d'`

i like dirs!

**Comment by akinomyoga** [comment] 2022-06-07 22:05
Thank you for the report! Hmm, to resolve the conflict, I think we need to rename the name of either one. However, it's difficult to decide which one to preserve and which one to change because some people want one and some other people want the other. In this case, you can just re-override the alias by yourself after sourcing oh-my-bash in your `.bashrc`. Do you have a better idea to resolve the issue on the oh-my-bash side in your mind?

**Comment by akinomyoga** [comment] 2022-09-29 11:27
I realized this is actually a duplicate of #63. I'll close it in favor of #63.

**Comment by akinomyoga** [comment] 2022-09-29 11:27
If you have replies or further comments, please reply in #63. Thank you!

**Closed by akinomyoga** 2022-09-29 11:27 UTC
Labels: duplicate
