### ISSUE TITLE
lesspipe in gentoo differs from ubuntu

### ISSUE THREAD

**Issue by wingedfox** [ohmybash/oh-my-bash#46] opened 2019-02-21 09:27 UTC
Hello,

`lesspipe` available in gentoo does not export vars and eval fails with error
```
$ [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/bash lesspipe)"
bash: syntax error near unexpected token `newline'
```

**Comment by Kreyren** [comment] 2019-07-24 01:57
Duplicate of https://github.com/ohmybash/oh-my-bash/issues/46

**Comment by Kreyren** [comment] 2019-07-24 02:00
```bash
rogisek / #  [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/bash lesspipe)"
bash: syntax error near unexpected token `newline'
```

Same issue on my gentoo

**Comment by Kreyren** [comment] 2019-07-24 02:07
@wingedfox && @Cowboy0 requesting testing for #74

**Comment by Kreyren** [comment] 2019-08-15 12:24
Assigned P2 since this is compatibility for Gentoo and simmilar likely to occur in stable release soon.

**Comment by AguilarSolutions** [comment] 2020-05-23 21:13
Hello!
Congratulations for this awesome project.
I'm a gentoo user and facing this problem with `lesspipe`
Please, is there any update to solve this issue?

**Comment by marshall-mcmullen** [comment] 2021-01-08 04:36
I modified `~/.oh-my-bash/lib/bourne-shell.sh` and just commented out `[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"`. I have no idea what impact that will have but the problem went away ;-)

**Comment by holmofy** [comment] 2021-08-11 15:48
Has this problem been solved?

**Comment by IPlayZed** [comment] 2022-01-02 14:54
> Has this problem been solved?

No, this still persists.

**Closed** 2022-01-18 05:15 UTC
Labels: P2 - Important
