### ISSUE TITLE
clicking on screenshots in README gives an error

### ISSUE THREAD

**Issue by samqi** [ohmybash/oh-my-bash#51] opened 2019-04-29 03:23 UTC
Click on screenshots in the README.md in root folder, birings us to this URL https://wiki.github.com/ohmybash/oh-my-bash/themes and  gives this message:
```
We didn't receive a proper request from your browser. Please contact us if the problem persists.
```

**Comment by Kreyren** [comment] 2019-07-24 01:53
There is just one image (https://cloud.githubusercontent.com/assets/2618447/6316862/70f58fb6-ba03-11e4-82c9-c083bf9a6574.png) in README.md which works for me 

Assuming invalid issue

**Comment by Kreyren** [comment] 2019-08-15 12:27
Closing as invalid or outdated. If the issue is still present then let me know and i will re-open.

**Closed by Kreyren** 2019-08-15 12:27 UTC
Labels: P3 - Normal
