### ISSUE TITLE
BASH ERROR

### ISSUE THREAD

**Issue by Cowboy0** [ohmybash/oh-my-bash#69] opened 2019-07-19 11:57 UTC
Hi All
I am trying to use OH-MY-BASH on a Gentoo system and when I load into my terminal after installation I am getting 2 errors as I am new to programming and scripting I am unable to recognize where the error is in any of the files can some please help 

bash: eval: line 6: syntax error near unexpected token `newline'
bash: eval: line 6: `Usage: lesspipe <file>'

**Comment by Kreyren** [comment] 2019-07-24 01:46
@Cowboy0  Try using latest version 

if issue is still present then show me your `~/.bashrc` for example using `cat $HOME/.bashrc | curl -n -F 'f:1=<-' http://ix.io` (assuming curl installed).

Suspecting syntax err on line 6 which should be `OSH_THEME="THEME_HERE"`

**Comment by Kreyren** [comment] 2019-07-24 01:57
Duplicate of https://github.com/ohmybash/oh-my-bash/issues/46

**Comment by Kreyren** [comment] 2019-08-13 10:25
Closing as duplicate of #46

**Closed by Kreyren** 2019-08-13 10:25 UTC
