### ISSUE TITLE
GitBash on windows: syntax error

### ISSUE THREAD

**Issue by tuxerrante** [ohmybash/oh-my-bash#260] opened 2021-11-25 15:15 UTC
Hi
I'm getting this error 
![image](https://user-images.githubusercontent.com/8364469/143466142-5a21dd34-f555-4355-9a53-fc4a36d068fa.png)

https://github.com/ohmybash/oh-my-bash/blob/4db7436384e0ddfa62911a101b69dd03a0df53fe/themes/cupcake/cupcake.theme.sh#L74

**Comment by akinomyoga** [comment] 2022-08-17 00:09
This seems to be a duplicate of #211.

**Comment by akinomyoga** [comment] 2022-08-18 01:53
See https://github.com/ohmybash/oh-my-bash/issues/211#issuecomment-1218903376. This is a problem with Git Bash (Git for Windows). Please update your Git Bash:

```bash
$ git update-git-for-windows
```

**Closed by akinomyoga** 2022-08-18 01:53 UTC
