### ISSUE TITLE
After uninstalling oh-my-zsh and installing oh-my-bash zsh still $SHELL

### ISSUE THREAD

**Issue by haug1** [ohmybash/oh-my-bash#212] opened 2021-04-03 21:06 UTC
Honestly not sure where to put this. 
I uninstalled oh-my-zsh and installed oh-my-bash, $SHELL was still /bin/zsh, but new terminals opened with /bin/bash.
After reboot $SHELL was set to /bin/bash

**Comment by iwconfig** [comment] 2021-07-23 17:53
I don't get it, what is the problem? This is normal. Did you not uninstall `oh-my-zsh` while under `zsh`?

I mean, the reason why `$SHELL` is still `/bin/zsh` is because that is the shell still running as the default in that specific terminal. You have to open a new terminal session for it to execute the newly set default login shell. This is specified in `/etc/passwd`, hence why `$SHELL` is `/bin/bash` after you installed `oh-my-bash`, only after opening a new terminal session, because it set `bash` as the default by editing the passwd file and because the terminal only declares $SHELL once.

In other words, the terminal runs the default shell and `$SHELL` reflects this. Changing the variable `$SHELL` to a different shell, or to whatever, in the current session has no effect (except for certain scripts and programs that is dependent on $SHELL to know what they're dealing with) and won't work regardless of which shell you're currently under.

![image](https://user-images.githubusercontent.com/10843441/126818429-e150ee77-9819-4d7d-96f4-a3ca99c27b49.png)

You can manually edit `/etc/passwd`, or run

    chsh -s /path/to/your/favourite/shell yourusername

 to change the default login shell.

**Comment by akinomyoga** [comment] 2021-12-29 03:05
I believe this is not an issue, so let me close it.

This is just intended behavior. The environment variable `SHELL` contains "*the path to the user's default shell*" when the current login session has started. The variable `SHELL` is *NOT* supposed to contain "*the path to the current shell*" as many people might consider. To check the current shell, you may check the value of `$BASH_VERSION` or `$ZSH_VERSION`.

**Closed by akinomyoga** 2021-12-29 03:05 UTC
